#! /usr/bin/env python
import os
import csv
import requests
import gzip
from subprocess import check_output
from collections import defaultdict

wildcard_constraints:
    runid = 'SRR[0-9]{6,9}', # runid must start with 'SRR', followed by 6-9 digits
    samid = 'SAMN[0-9]{6,9}'  # samid must start with 'GSM', followed by 6-9 digits

configfile: "config/config.yaml"

with open(config['sample_csv'], 'r') as csvfile:
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
    csvfile.seek(0)
    METADATA = [row for row in csv.DictReader(csvfile)]

SAMPLES = [d[config['colname_SAMPLE']] for d in METADATA]
RUNS = [d[config['colname_RUN']] for d in METADATA]

SAMPLE_RUN = defaultdict(list)
for d in METADATA:
    SAMPLE_RUN[d[config['colname_SAMPLE']]].append(d[config['colname_RUN']])

rule all:
    input:
        expand("results/telescope/{samid}_telescope_completed.txt", samid=SAMPLES)

include: "rules/fasterq_dump.smk"
include: "rules/references.smk"
include: "rules/star_index.smk"
include: "rules/star_alignment.smk"
include: "rules/telescope.smk"
# include: "rules/sample_complete.smk"
