sample_csv: "config/samples_riboseq.csv"

# Column names for sample and run
colname_SAMPLE: "BioSample"
colname_RUN: "Run"
colname_library: "LibraryLayout"

# assigned temporary directory
local_tmp: "$TMPDIR"

# Remote databases or resources to be downloaded
downloads:
  GRCh38.d1.vd1.fa.tar.gz:
    url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
    md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
  gencode.v38.annotation.gtf.gz:
    url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
    md5: "16fcae8ca8e488cd8056cf317d963407"
  retro.hg38.v1.gtf:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/transcripts.gtf"
    md5: "c07cf115c1f957b3020efc547f3847fa"
  retro.hg38.v1.tsv.gz:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/genes.tsv.gz"
    md5: "b3ca6d3705d030742255d216e25dfc1d"

downloads_hervquant:
  hervquant_final_reference.fa:
    url: "https://unclineberger.org/vincentlab/wp-content/uploads/sites/1083/2020/10/hervquant-reference-file.zip"
  hervquant_hg19_reference.fa:
    url: "https://unclineberger.org/vincentlab/wp-content/uploads/sites/1083/2020/10/hervquant_hg19_reference.fa_.zip"

sequences:
    genome: "databases/sequences/gdc38.fna"
    genome_idx: "databases/sequences/gdc38.fna.fai"
    genome_dict: "databases/sequences/gdc38.dict"
    hervquant_final: "databases/remotefiles/hervquant_final_reference.fa"
    hervquant_hg19: "databases/remotefiles/hervquant_hg19_reference.fa"

indexes:
    star: "databases/indexes/STAR_gdc38_gencode38"
    star_hervquant: "databases/indexes/STAR_hervquant_hg19"

annotations:
    gencode: "databases/downloads/gencode.v38.annotation.gtf.gz"
    retro: "databases/annotations/retro.hg38.v1.gtf"
    retro_tsv: "databases/annotations/retro.hg38.v1.tsv.gz"

# fasterq dump parameters
fasterq_dump_tmp:  "/fsx/projects/follicular_lymphoma_TE_atlas/runs/"

# STAR genome index parameters
splice_junction_overhang: 74
star_index_threads: 24
star_index_mem_mb: 40000
local_tmp: "$TMPDIR"

# STAR alignment parameters
star_alignment_threads: 24
outFilterMultimapNmax: 200
winAnchorMultimapNmax: 200

# TELESCOPE
telescope_threads: 4
# FINAL OUTPUT dirname

efs_dir_star: "/efs/projects/te_riboseq_atlas/star_algn/"
efs_dir_telescope: "/efs/projects/te_riboseq_atlas/telescope/"
